### ISSUE TITLE
Escrita do artigo pyCOFBuilder

### ISSUE THREAD

**Issue by lipelopesoliveira** [lipelopesoliveira/pyCOFBuilder#5]
### O que deve ser feito?

Escrita do artigo do pyCOFBuilder, descrevendo suas principais funcionalidades, benchmarks dos resultados e tudo mais. 

### O que será obtido ao final dessa tarefa?

Versão do artigo pronta para submissão. 

### Possui prazo limite ce conclusão?

Não

### Mais alguma outra coisa?

Link para o artigo: https://www.overleaf.com/project/62a8cd22f2ce185d3524a4e7

### Introdução

- [x] O que são COFs e quais são suas aplicações
- [x] Química reticular e suas vantagens
- [x] Cálculos _high-througput_ como novo paradigma da pesquisa
- [x] Banco de dados existentes e suas limitações
- [x] Apresentação do pyCOFbuilder e descrição das principais características e resultados

### Resultados
- [x] Explicar o racional por trás da nonemclatura 
- [x] Explicar em detalhes a forma de construção dos `Building Blocks`
- [x] Explicar em detalhes a forma de construção de um `Reticulum`
- [x] Explicar em detalhes a organização do código e funcionamento das classes.
- [x] Mostrar um exemplo de utilização para construção de uma estrutura específica e discutir possibilidade de geração de múltiplas variantes estruturais
- [ ] #31
- [x] Otimizar as estruturas geradas pelo pyCOFBuilder e analisar se na média o resultado muda muito.
- [x] Explorar aplicação para captura de gases poluentes.

### Metodologia
 - [ ] Métodos DFT
 - [ ] Métodos para o cálculo de cargas parciais
 - [ ] Motodologia GCMC

## To-do

- [ ] Refazer Figura 1 do artigo. 
  - Essa figura devera apresentar de maneira simples e clara o processo de criação da estrutura a partir dos conceitos de Química Reticular.
- [ ] Preparar Figura 2 do artigo.
  - Essa figura deverá ser um painel, que apresente vários conceitos em uma figura só. Texto provisório de descrição da figura:
 
> Example of organic cores, connection groups and functional groups available to generate a COF structures. The organic cores are enconded on the COF string representation using the four letter code presented below the structures. Although arbitrarily defined, the letters are thought to represent an abbreviation of the IUPAC name of the molecule from which the organic core is derived. Q marks the position of the connection groups and Rx marks the position of the functional groups. Both the connection group and functional groups are encoded using the common chemistry abreviation
